spring:
  application:
    name: clients-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql
  flyway:
    enabled: false

server:
  port: 8082
