spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql
  flyway:
    enabled: false

app:
  limits:
    default: 10000

server:
  port: 8081

integrations:
  clients-info-service:
    url: "http://localhost:8082/api/v1/clients"