server:
  port: 8189
spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql

integrations:
  clients-info-service:
    url: "http://localhost:8826/clients-service/api/v1/clients"
    read-timeout: 30s
    write-timeout: 2s
  limits-service:
    url: "http://localhost:8822/limits-service/api/v1/limits"
    read-timeout: 20s
    write-timeout: 1s

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
